#include "Settings.hpp"

const float Settings::DEFAULT_CAMERA_ROTATION_SPEED_IN_TURNS_PER_INCH = 0.05f;
const float Settings::DEFAULT_CAMERA_TRANSLATION_SPEED_PER_INCH = 0.07f;
const float Settings::DEFAULT_CAMERA_SCALE_RADIUS_PER_SCROLL = 0.9f;

float Settings::CAMERA_ROTATION_SPEED_IN_TURNS_PER_INCH = DEFAULT_CAMERA_ROTATION_SPEED_IN_TURNS_PER_INCH;
float Settings::CAMERA_TRANSLATION_SPEED_PER_INCH = DEFAULT_CAMERA_TRANSLATION_SPEED_PER_INCH;
float Settings::CAMERA_SCALE_RADIUS_PER_SCROLL = DEFAULT_CAMERA_SCALE_RADIUS_PER_SCROLL;