#pragma once

struct Settings {
	static const float DEFAULT_CAMERA_ROTATION_SPEED_IN_TURNS_PER_INCH;
	static const float DEFAULT_CAMERA_TRANSLATION_SPEED_PER_INCH;
	static const float DEFAULT_CAMERA_SCALE_RADIUS_PER_SCROLL;

	static float CAMERA_ROTATION_SPEED_IN_TURNS_PER_INCH;
	static float CAMERA_TRANSLATION_SPEED_PER_INCH;
	static float CAMERA_SCALE_RADIUS_PER_SCROLL;
};